version: "3.9"
services:
  sqs-s3-consumer:
    build:
      dockerfile: sqs-s3-event-consumer.dockerfile
    container_name: sqs-s3-consumer
    restart: always
    environment:
      # Inject all variables here
      SQS_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/726573357412/s3-notify-queue"
      MAX_MESSAGES: 10
      WAIT_TIME_SECONDS: 10
      VISIBILITY_TIMEOUT_SECONDS: 30
      DOWNLOAD_DIR: "/home/rocky/SQS_demo/Version_2/data/download9s"
      AWS_DEFAULT_REGION: "us-east-1"
    volumes:
      - ./downloads:/data/downloads
      - ~/.aws:/root/.aws:ro   # use local AWS credentials
